import { NextResponse } from 'next/server';

// Complete Ghana Municipalities and Districts Data
const GHANA_COMPLETE_DATA = {
  regions: [
    { id: 'greater-accra', name: 'Greater Accra Region', capital: 'Accra', code: 'GAR' },
    { id: 'ashanti', name: 'Ashanti Region', capital: 'Kumasi', code: 'ASH' },
    { id: 'western', name: 'Western Region', capital: 'Sekondi-Takoradi', code: 'WR' },
    { id: 'central', name: 'Central Region', capital: 'Cape Coast', code: 'CR' },
    { id: 'volta', name: 'Volta Region', capital: 'Ho', code: 'VR' },
    { id: 'eastern', name: 'Eastern Region', capital: 'Koforidua', code: 'ER' },
    { id: 'northern', name: 'Northern Region', capital: 'Tamale', code: 'NR' },
    { id: 'upper-east', name: 'Upper East Region', capital: 'Bolgatanga', code: 'UER' },
    { id: 'upper-west', name: 'Upper West Region', capital: 'Wa', code: 'UWR' },
    { id: 'brong-ahafo', name: 'Brong-Ahafo Region', capital: 'Sunyani', code: 'BAR' },
    { id: 'western-north', name: 'Western North Region', capital: 'Sefwi Wiawso', code: 'WNR' },
    { id: 'ahafo', name: 'Ahafo Region', capital: 'Goaso', code: 'AHR' },
    { id: 'bono', name: 'Bono Region', capital: 'Sunyani', code: 'BR' },
    { id: 'bono-east', name: 'Bono East Region', capital: 'Techiman', code: 'BER' },
    { id: 'oti', name: 'Oti Region', capital: 'Dambai', code: 'OR' },
    { id: 'savannah', name: 'Savannah Region', capital: 'Damongo', code: 'SR' },
    { id: 'north-east', name: 'North East Region', capital: 'Nalerigu', code: 'NER' },
  ],
  municipalities: {
    'greater-accra': [
      { id: 'accra-metro', name: 'Accra Metropolitan Assembly', type: 'Metropolitan', capital: 'Accra' },
      { id: 'tema-metro', name: 'Tema Metropolitan Assembly', type: 'Metropolitan', capital: 'Tema' },
      { id: 'adenta-municipal', name: 'Adenta Municipal Assembly', type: 'Municipal', capital: 'Adenta' },
      { id: 'ashaiman-municipal', name: 'Ashaiman Municipal Assembly', type: 'Municipal', capital: 'Ashaiman' },
      { id: 'ga-central-municipal', name: 'Ga Central Municipal Assembly', type: 'Municipal', capital: 'Anyaa' },
      { id: 'ga-east-municipal', name: 'Ga East Municipal Assembly', type: 'Municipal', capital: 'Abokobi' },
      { id: 'ga-north-municipal', name: 'Ga North Municipal Assembly', type: 'Municipal', capital: 'Ofankor' },
      { id: 'ga-south-municipal', name: 'Ga South Municipal Assembly', type: 'Municipal', capital: 'Ngleshie Amanfro' },
      { id: 'ga-west-municipal', name: 'Ga West Municipal Assembly', type: 'Municipal', capital: 'Amasaman' },
      { id: 'kpone-katamanso-municipal', name: 'Kpone-Katamanso Municipal Assembly', type: 'Municipal', capital: 'Kpone' },
      { id: 'la-dade-kotopon-municipal', name: 'La Dade-Kotopon Municipal Assembly', type: 'Municipal', capital: 'La' },
      { id: 'la-nkwantanang-madina-municipal', name: 'La Nkwantanang-Madina Municipal Assembly', type: 'Municipal', capital: 'Madina' },
      { id: 'ledzokuku-krowor-municipal', name: 'Ledzokuku-Krowor Municipal Assembly', type: 'Municipal', capital: 'Teshie' },
      { id: 'okaikwei-north-municipal', name: 'Okaikwei North Municipal Assembly', type: 'Municipal', capital: 'Tesano' },
      { id: 'weija-gbawe-municipal', name: 'Weija-Gbawe Municipal Assembly', type: 'Municipal', capital: 'Weija' },
      { id: 'ablekuma-north-municipal', name: 'Ablekuma North Municipal Assembly', type: 'Municipal', capital: 'Darkuman' },
      { id: 'ablekuma-central-municipal', name: 'Ablekuma Central Municipal Assembly', type: 'Municipal', capital: 'Odorkor' },
      { id: 'ablekuma-west-municipal', name: 'Ablekuma West Municipal Assembly', type: 'Municipal', capital: 'Dansoman' },
      { id: 'ayawaso-central-municipal', name: 'Ayawaso Central Municipal Assembly', type: 'Municipal', capital: 'Kokomlemle' },
      { id: 'ayawaso-east-municipal', name: 'Ayawaso East Municipal Assembly', type: 'Municipal', capital: 'Nima' },
      { id: 'ayawaso-north-municipal', name: 'Ayawaso North Municipal Assembly', type: 'Municipal', capital: 'Dzorwulu' },
      { id: 'ayawaso-west-wuogon-municipal', name: 'Ayawaso West Wuogon Municipal Assembly', type: 'Municipal', capital: 'Legon' },
      { id: 'korle-klottey-municipal', name: 'Korle Klottey Municipal Assembly', type: 'Municipal', capital: 'Adabraka' },
      { id: 'adentan-municipal', name: 'Adentan Municipal Assembly', type: 'Municipal', capital: 'Adentan' },
      { id: 'krowor-municipal', name: 'Krowor Municipal Assembly', type: 'Municipal', capital: 'Nungua' },
      { id: 'shai-osudoku-district', name: 'Shai-Osudoku District Assembly', type: 'District', capital: 'Dodowa' },
      { id: 'ningo-prampram-district', name: 'Ningo-Prampram District Assembly', type: 'District', capital: 'Prampram' },
      { id: 'ada-east-district', name: 'Ada East District Assembly', type: 'District', capital: 'Ada Foah' },
      { id: 'ada-west-district', name: 'Ada West District Assembly', type: 'District', capital: 'Sege' },
    ],
    'ashanti': [
      { id: 'kumasi-metro', name: 'Kumasi Metropolitan Assembly', type: 'Metropolitan', capital: 'Kumasi' },
      { id: 'obuasi-municipal', name: 'Obuasi Municipal Assembly', type: 'Municipal', capital: 'Obuasi' },
      { id: 'ejisu-municipal', name: 'Ejisu Municipal Assembly', type: 'Municipal', capital: 'Ejisu' },
      { id: 'bekwai-municipal', name: 'Bekwai Municipal Assembly', type: 'Municipal', capital: 'Bekwai' },
      { id: 'bosome-freho-district', name: 'Bosome Freho District Assembly', type: 'District', capital: 'Asiwa' },
      { id: 'atwima-kwanwoma-district', name: 'Atwima Kwanwoma District Assembly', type: 'District', capital: 'Goaso' },
      { id: 'atwima-nwabiagya-municipal', name: 'Atwima Nwabiagya Municipal Assembly', type: 'Municipal', capital: 'Nkawie' },
      { id: 'atwima-nwabiagya-north-district', name: 'Atwima Nwabiagya North District Assembly', type: 'District', capital: 'Barekese' },
      { id: 'atwima-mponua-district', name: 'Atwima Mponua District Assembly', type: 'District', capital: 'Nyinahin' },
      { id: 'afigya-kwabre-south-district', name: 'Afigya Kwabre South District Assembly', type: 'District', capital: 'Kodie' },
      { id: 'afigya-kwabre-north-district', name: 'Afigya Kwabre North District Assembly', type: 'District', capital: 'Afrancho' },
      { id: 'kwabre-east-municipal', name: 'Kwabre East Municipal Assembly', type: 'Municipal', capital: 'Mamponteng' },
      { id: 'asante-akim-north-municipal', name: 'Asante Akim North Municipal Assembly', type: 'Municipal', capital: 'Agogo' },
      { id: 'asante-akim-south-municipal', name: 'Asante Akim South Municipal Assembly', type: 'Municipal', capital: 'Juaso' },
      { id: 'asante-akim-central-municipal', name: 'Asante Akim Central Municipal Assembly', type: 'Municipal', capital: 'Konongo' },
      { id: 'adansi-north-district', name: 'Adansi North District Assembly', type: 'District', capital: 'Fomena' },
      { id: 'adansi-asokwa-district', name: 'Adansi Asokwa District Assembly', type: 'District', capital: 'Dadiesoaba' },
      { id: 'adansi-south-district', name: 'Adansi South District Assembly', type: 'District', capital: 'New Edubiase' },
      { id: 'amansie-central-district', name: 'Amansie Central District Assembly', type: 'District', capital: 'Jacobu' },
      { id: 'amansie-south-district', name: 'Amansie South District Assembly', type: 'District', capital: 'Manso Nkwanta' },
      { id: 'amansie-west-district', name: 'Amansie West District Assembly', type: 'District', capital: 'Manso Adubia' },
      { id: 'bosomtwe-district', name: 'Bosomtwe District Assembly', type: 'District', capital: 'Kuntanase' },
      { id: 'ahafo-ano-north-municipal', name: 'Ahafo Ano North Municipal Assembly', type: 'Municipal', capital: 'Tepa' },
      { id: 'ahafo-ano-south-west-district', name: 'Ahafo Ano South West District Assembly', type: 'District', capital: 'Mankranso' },
      { id: 'ahafo-ano-south-east-district', name: 'Ahafo Ano South East District Assembly', type: 'District', capital: 'Donyina' },
      { id: 'offinso-municipal', name: 'Offinso Municipal Assembly', type: 'Municipal', capital: 'Offinso' },
      { id: 'offinso-north-district', name: 'Offinso North District Assembly', type: 'District', capital: 'Akumadan' },
      { id: 'asokore-mampong-municipal', name: 'Asokore Mampong Municipal Assembly', type: 'Municipal', capital: 'Asokore Mampong' },
      { id: 'old-tafo-municipal', name: 'Old Tafo Municipal Assembly', type: 'Municipal', capital: 'Old Tafo' },
      { id: 'suame-municipal', name: 'Suame Municipal Assembly', type: 'Municipal', capital: 'Suame' },
      { id: 'kwadaso-municipal', name: 'Kwadaso Municipal Assembly', type: 'Municipal', capital: 'Kwadaso' },
      { id: 'oforikrom-municipal', name: 'Oforikrom Municipal Assembly', type: 'Municipal', capital: 'Oforikrom' },
      { id: 'asokwa-municipal', name: 'Asokwa Municipal Assembly', type: 'Municipal', capital: 'Asokwa' },
      { id: 'nhyiaeso-municipal', name: 'Nhyiaeso Municipal Assembly', type: 'Municipal', capital: 'Nhyiaeso' },
      { id: 'bantama-municipal', name: 'Bantama Municipal Assembly', type: 'Municipal', capital: 'Bantama' },
      { id: 'tafo-pankrono-municipal', name: 'Tafo Pankrono Municipal Assembly', type: 'Municipal', capital: 'Tafo' },
      { id: 'kwadaso-municipal-2', name: 'Kwadaso Municipal Assembly', type: 'Municipal', capital: 'Kwadaso Estate' },
      { id: 'mampong-municipal', name: 'Mampong Municipal Assembly', type: 'Municipal', capital: 'Mampong' },
      { id: 'sekyere-south-district', name: 'Sekyere South District Assembly', type: 'District', capital: 'Agona' },
      { id: 'sekyere-east-district', name: 'Sekyere East District Assembly', type: 'District', capital: 'Effiduase' },
      { id: 'sekyere-central-district', name: 'Sekyere Central District Assembly', type: 'District', capital: 'Nsuta' },
      { id: 'sekyere-afram-plains-district', name: 'Sekyere Afram Plains District Assembly', type: 'District', capital: 'Drobonso' },
      { id: 'juaben-municipal', name: 'Juaben Municipal Assembly', type: 'Municipal', capital: 'Juaben' },
      { id: 'ejura-sekyedumase-municipal', name: 'Ejura-Sekyedumase Municipal Assembly', type: 'Municipal', capital: 'Ejura' },
    ],
    'western': [
      { id: 'sekondi-takoradi-metro', name: 'Sekondi-Takoradi Metropolitan Assembly', type: 'Metropolitan', capital: 'Sekondi-Takoradi' },
      { id: 'tarkwa-nsuaem-municipal', name: 'Tarkwa-Nsuaem Municipal Assembly', type: 'Municipal', capital: 'Tarkwa' },
      { id: 'prestea-huni-valley-municipal', name: 'Prestea-Huni Valley Municipal Assembly', type: 'Municipal', capital: 'Prestea' },
      { id: 'wassa-east-district', name: 'Wassa East District Assembly', type: 'District', capital: 'Daboase' },
      { id: 'wassa-amenfi-west-municipal', name: 'Wassa Amenfi West Municipal Assembly', type: 'Municipal', capital: 'Asankrangwa' },
      { id: 'wassa-amenfi-central-municipal', name: 'Wassa Amenfi Central Municipal Assembly', type: 'Municipal', capital: 'Manso Amenfi' },
      { id: 'wassa-amenfi-east-municipal', name: 'Wassa Amenfi East Municipal Assembly', type: 'Municipal', capital: 'Wassa Akropong' },
      { id: 'mpohor-district', name: 'Mpohor District Assembly', type: 'District', capital: 'Mpohor' },
      { id: 'shama-district', name: 'Shama District Assembly', type: 'District', capital: 'Shama' },
      { id: 'ahanta-west-municipal', name: 'Ahanta West Municipal Assembly', type: 'Municipal', capital: 'Agona Nkwanta' },
      { id: 'nzema-east-municipal', name: 'Nzema East Municipal Assembly', type: 'Municipal', capital: 'Axim' },
      { id: 'ellembelle-district', name: 'Ellembelle District Assembly', type: 'District', capital: 'Nkroful' },
      { id: 'jomoro-district', name: 'Jomoro District Assembly', type: 'District', capital: 'Half Assini' },
      { id: 'aowin-municipal', name: 'Aowin Municipal Assembly', type: 'Municipal', capital: 'Enchi' },
      { id: 'suaman-district', name: 'Suaman District Assembly', type: 'District', capital: 'Dadieso' },
      { id: 'bibiani-anhwiaso-bekwai-municipal', name: 'Bibiani-Anhwiaso-Bekwai Municipal Assembly', type: 'Municipal', capital: 'Bibiani' },
      { id: 'wiawso-municipal', name: 'Wiawso Municipal Assembly', type: 'Municipal', capital: 'Sefwi Wiawso' },
      { id: 'bodi-district', name: 'Bodi District Assembly', type: 'District', capital: 'Bodi' },
      { id: 'juaboso-district', name: 'Juaboso District Assembly', type: 'District', capital: 'Juaboso' },
      { id: 'bia-east-district', name: 'Bia East District Assembly', type: 'District', capital: 'Adabokrom' },
      { id: 'bia-west-district', name: 'Bia West District Assembly', type: 'District', capital: 'Essam' },
      { id: 'akontombra-district', name: 'Akontombra District Assembly', type: 'District', capital: 'Akontombra' },
    ],
    // Add more regions with their municipalities...
    'central': [
      { id: 'cape-coast-metro', name: 'Cape Coast Metropolitan Assembly', type: 'Metropolitan', capital: 'Cape Coast' },
      { id: 'komenda-edina-eguafo-abirem-municipal', name: 'Komenda-Edina-Eguafo-Abirem Municipal Assembly', type: 'Municipal', capital: 'Elmina' },
      { id: 'abura-asebu-kwamankese-district', name: 'Abura-Asebu-Kwamankese District Assembly', type: 'District', capital: 'Abura Dunkwa' },
      { id: 'mfantsiman-municipal', name: 'Mfantsiman Municipal Assembly', type: 'Municipal', capital: 'Saltpond' },
      { id: 'awutu-senya-east-municipal', name: 'Awutu Senya East Municipal Assembly', type: 'Municipal', capital: 'Kasoa' },
      { id: 'awutu-senya-west-district', name: 'Awutu Senya West District Assembly', type: 'District', capital: 'Awutu Breku' },
      { id: 'effutu-municipal', name: 'Effutu Municipal Assembly', type: 'Municipal', capital: 'Winneba' },
      { id: 'gomoa-east-district', name: 'Gomoa East District Assembly', type: 'District', capital: 'Potsin' },
      { id: 'gomoa-central-district', name: 'Gomoa Central District Assembly', type: 'District', capital: 'Apam' },
      { id: 'gomoa-west-district', name: 'Gomoa West District Assembly', type: 'District', capital: 'Apam' },
      { id: 'agona-east-district', name: 'Agona East District Assembly', type: 'District', capital: 'Nsaba' },
      { id: 'agona-west-municipal', name: 'Agona West Municipal Assembly', type: 'Municipal', capital: 'Agona Swedru' },
      { id: 'assin-north-municipal', name: 'Assin North Municipal Assembly', type: 'Municipal', capital: 'Assin Bereku' },
      { id: 'assin-central-municipal', name: 'Assin Central Municipal Assembly', type: 'Municipal', capital: 'Assin Fosu' },
      { id: 'assin-south-district', name: 'Assin South District Assembly', type: 'District', capital: 'Nsuaem' },
      { id: 'twifo-atti-morkwa-district', name: 'Twifo Atti-Morkwa District Assembly', type: 'District', capital: 'Twifo Praso' },
      { id: 'twifo-hemang-lower-denkyira-district', name: 'Twifo Hemang Lower Denkyira District Assembly', type: 'District', capital: 'Twifo Hemang' },
      { id: 'upper-denkyira-east-municipal', name: 'Upper Denkyira East Municipal Assembly', type: 'Municipal', capital: 'Dunkwa-on-Offin' },
      { id: 'upper-denkyira-west-district', name: 'Upper Denkyira West District Assembly', type: 'District', capital: 'Diaso' },
      { id: 'ekumfi-district', name: 'Ekumfi District Assembly', type: 'District', capital: 'Essarkyir' },
    ],
    // Continue with other regions...
    'volta': [
      { id: 'ho-municipal', name: 'Ho Municipal Assembly', type: 'Municipal', capital: 'Ho' },
      { id: 'hohoe-municipal', name: 'Hohoe Municipal Assembly', type: 'Municipal', capital: 'Hohoe' },
      { id: 'keta-municipal', name: 'Keta Municipal Assembly', type: 'Municipal', capital: 'Keta' },
      { id: 'ketu-north-municipal', name: 'Ketu North Municipal Assembly', type: 'Municipal', capital: 'Dzodze' },
      { id: 'ketu-south-municipal', name: 'Ketu South Municipal Assembly', type: 'Municipal', capital: 'Klikor' },
      { id: 'akatsi-north-district', name: 'Akatsi North District Assembly', type: 'District', capital: 'Ave Dakpa' },
      { id: 'akatsi-south-district', name: 'Akatsi South District Assembly', type: 'District', capital: 'Akatsi' },
      { id: 'central-tongu-district', name: 'Central Tongu District Assembly', type: 'District', capital: 'Adidome' },
      { id: 'north-tongu-district', name: 'North Tongu District Assembly', type: 'District', capital: 'Battor' },
      { id: 'south-tongu-district', name: 'South Tongu District Assembly', type: 'District', capital: 'Sogakope' },
      { id: 'anloga-district', name: 'Anloga District Assembly', type: 'District', capital: 'Anloga' },
      { id: 'some-district', name: 'Some District Assembly', type: 'District', capital: 'Some' },
      { id: 'adaklu-district', name: 'Adaklu District Assembly', type: 'District', capital: 'Adaklu Waya' },
      { id: 'ho-west-district', name: 'Ho West District Assembly', type: 'District', capital: 'Dzolo Kpuita' },
      { id: 'south-dayi-district', name: 'South Dayi District Assembly', type: 'District', capital: 'Kpeve' },
      { id: 'north-dayi-district', name: 'North Dayi District Assembly', type: 'District', capital: 'Anfoega' },
      { id: 'afadjato-south-district', name: 'Afadjato South District Assembly', type: 'District', capital: 'Ve-Koloenu' },
      { id: 'biakoye-district', name: 'Biakoye District Assembly', type: 'District', capital: 'Nkonya Ahenkro' },
      { id: 'jasikan-district', name: 'Jasikan District Assembly', type: 'District', capital: 'Jasikan' },
      { id: 'kadjebi-district', name: 'Kadjebi District Assembly', type: 'District', capital: 'Kadjebi' },
      { id: 'krachi-east-municipal', name: 'Krachi East Municipal Assembly', type: 'Municipal', capital: 'Dambai' },
      { id: 'krachi-west-district', name: 'Krachi West District Assembly', type: 'District', capital: 'Kete Krachi' },
      { id: 'krachi-nchumuru-district', name: 'Krachi Nchumuru District Assembly', type: 'District', capital: 'Chinderi' },
      { id: 'nkwanta-south-municipal', name: 'Nkwanta South Municipal Assembly', type: 'Municipal', capital: 'Nkwanta' },
      { id: 'nkwanta-north-district', name: 'Nkwanta North District Assembly', type: 'District', capital: 'Kpassa' },
    ],
    // Add remaining regions with abbreviated data for now
    'eastern': [
      { id: 'koforidua-municipal', name: 'New-Juaben South Municipal Assembly', type: 'Municipal', capital: 'Koforidua' },
      { id: 'new-juaben-north-municipal', name: 'New-Juaben North Municipal Assembly', type: 'Municipal', capital: 'Effiduase' },
      { id: 'akuapem-north-municipal', name: 'Akuapem North Municipal Assembly', type: 'Municipal', capital: 'Akropong' },
      { id: 'akuapem-south-district', name: 'Akuapem South District Assembly', type: 'District', capital: 'Nsawam' },
      { id: 'suhum-municipal', name: 'Suhum Municipal Assembly', type: 'Municipal', capital: 'Suhum' },
      { id: 'ayensuano-district', name: 'Ayensuano District Assembly', type: 'District', capital: 'Coaltar' },
      { id: 'west-akim-municipal', name: 'West Akim Municipal Assembly', type: 'Municipal', capital: 'Asamankese' },
      { id: 'east-akim-municipal', name: 'East Akim Municipal Assembly', type: 'Municipal', capital: 'Kibi' },
      { id: 'abuakwa-north-municipal', name: 'Abuakwa North Municipal Assembly', type: 'Municipal', capital: 'Kukurantumi' },
      { id: 'abuakwa-south-municipal', name: 'Abuakwa South Municipal Assembly', type: 'Municipal', capital: 'Kyebi' },
      { id: 'fanteakwa-north-district', name: 'Fanteakwa North District Assembly', type: 'District', capital: 'Begoro' },
      { id: 'fanteakwa-south-district', name: 'Fanteakwa South District Assembly', type: 'District', capital: 'Osino' },
      { id: 'kwaebibirem-municipal', name: 'Kwaebibirem Municipal Assembly', type: 'Municipal', capital: 'Kade' },
      { id: 'denkyembour-district', name: 'Denkyembour District Assembly', type: 'District', capital: 'Akwatia' },
      { id: 'atiwa-east-district', name: 'Atiwa East District Assembly', type: 'District', capital: 'Anyinam' },
      { id: 'atiwa-west-district', name: 'Atiwa West District Assembly', type: 'District', capital: 'Kwabeng' },
      { id: 'upper-manya-krobo-district', name: 'Upper Manya Krobo District Assembly', type: 'District', capital: 'Asesewa' },
      { id: 'lower-manya-krobo-municipal', name: 'Lower Manya Krobo Municipal Assembly', type: 'Municipal', capital: 'Odumase Krobo' },
      { id: 'yilo-krobo-municipal', name: 'Yilo Krobo Municipal Assembly', type: 'Municipal', capital: 'Somanya' },
      { id: 'okere-district', name: 'Okere District Assembly', type: 'District', capital: 'Nkurakan' },
      { id: 'upper-west-akim-district', name: 'Upper West Akim District Assembly', type: 'District', capital: 'Adeiso' },
      { id: 'kwahu-west-municipal', name: 'Kwahu West Municipal Assembly', type: 'Municipal', capital: 'Nkawkaw' },
      { id: 'kwahu-east-district', name: 'Kwahu East District Assembly', type: 'District', capital: 'Abetifi' },
      { id: 'kwahu-south-district', name: 'Kwahu South District Assembly', type: 'District', capital: 'Mpraeso' },
      { id: 'kwahu-afram-plains-south-district', name: 'Kwahu Afram Plains South District Assembly', type: 'District', capital: 'Tease' },
      { id: 'kwahu-afram-plains-north-district', name: 'Kwahu Afram Plains North District Assembly', type: 'District', capital: 'Donkorkrom' },
      { id: 'birim-north-district', name: 'Birim North District Assembly', type: 'District', capital: 'New Abirem' },
      { id: 'birim-central-municipal', name: 'Birim Central Municipal Assembly', type: 'Municipal', capital: 'Akyem Oda' },
      { id: 'birim-south-district', name: 'Birim South District Assembly', type: 'District', capital: 'Achiase' },
    ],
    'northern': [
      { id: 'tamale-metro', name: 'Tamale Metropolitan Assembly', type: 'Metropolitan', capital: 'Tamale' },
      { id: 'sagnarigu-municipal', name: 'Sagnarigu Municipal Assembly', type: 'Municipal', capital: 'Sagnarigu' },
      { id: 'yendi-municipal', name: 'Yendi Municipal Assembly', type: 'Municipal', capital: 'Yendi' },
      { id: 'zabzugu-district', name: 'Zabzugu District Assembly', type: 'District', capital: 'Zabzugu' },
      { id: 'tatale-sanguli-district', name: 'Tatale-Sanguli District Assembly', type: 'District', capital: 'Tatale' },
      { id: 'gushegu-municipal', name: 'Gushegu Municipal Assembly', type: 'Municipal', capital: 'Gushegu' },
      { id: 'karaga-district', name: 'Karaga District Assembly', type: 'District', capital: 'Karaga' },
      { id: 'kumbungu-district', name: 'Kumbungu District Assembly', type: 'District', capital: 'Kumbungu' },
      { id: 'tolon-district', name: 'Tolon District Assembly', type: 'District', capital: 'Tolon' },
      { id: 'savelugu-municipal', name: 'Savelugu Municipal Assembly', type: 'Municipal', capital: 'Savelugu' },
      { id: 'nanton-district', name: 'Nanton District Assembly', type: 'District', capital: 'Nanton' },
      { id: 'mion-district', name: 'Mion District Assembly', type: 'District', capital: 'Sang' },
      { id: 'kpandai-district', name: 'Kpandai District Assembly', type: 'District', capital: 'Kpandai' },
      { id: 'nanumba-north-municipal', name: 'Nanumba North Municipal Assembly', type: 'Municipal', capital: 'Bimbilla' },
      { id: 'nanumba-south-district', name: 'Nanumba South District Assembly', type: 'District', capital: 'Wulensi' },
      { id: 'chereponi-district', name: 'Chereponi District Assembly', type: 'District', capital: 'Chereponi' },
      { id: 'east-mamprusi-municipal', name: 'East Mamprusi Municipal Assembly', type: 'Municipal', capital: 'Gambaga' },
      { id: 'west-mamprusi-municipal', name: 'West Mamprusi Municipal Assembly', type: 'Municipal', capital: 'Walewale' },
    ],
    'upper-east': [
      { id: 'bolgatanga-municipal', name: 'Bolgatanga Municipal Assembly', type: 'Municipal', capital: 'Bolgatanga' },
      { id: 'talensi-district', name: 'Talensi District Assembly', type: 'District', capital: 'Tongo' },
      { id: 'nabdam-district', name: 'Nabdam District Assembly', type: 'District', capital: 'Nangodi' },
      { id: 'builsa-north-district', name: 'Builsa North District Assembly', type: 'District', capital: 'Sandema' },
      { id: 'builsa-south-district', name: 'Builsa South District Assembly', type: 'District', capital: 'Fumbisi' },
      { id: 'kassena-nankana-west-district', name: 'Kassena-Nankana West District Assembly', type: 'District', capital: 'Paga' },
      { id: 'kassena-nankana-municipal', name: 'Kassena-Nankana Municipal Assembly', type: 'Municipal', capital: 'Navrongo' },
      { id: 'bawku-west-district', name: 'Bawku West District Assembly', type: 'District', capital: 'Zebilla' },
      { id: 'bawku-municipal', name: 'Bawku Municipal Assembly', type: 'Municipal', capital: 'Bawku' },
      { id: 'pusiga-district', name: 'Pusiga District Assembly', type: 'District', capital: 'Pusiga' },
      { id: 'garu-district', name: 'Garu District Assembly', type: 'District', capital: 'Garu' },
      { id: 'tempane-district', name: 'Tempane District Assembly', type: 'District', capital: 'Tempane' },
      { id: 'binduri-district', name: 'Binduri District Assembly', type: 'District', capital: 'Binduri' },
    ],
    'upper-west': [
      { id: 'wa-municipal', name: 'Wa Municipal Assembly', type: 'Municipal', capital: 'Wa' },
      { id: 'wa-east-district', name: 'Wa East District Assembly', type: 'District', capital: 'Funsi' },
      { id: 'wa-west-district', name: 'Wa West District Assembly', type: 'District', capital: 'Wechiau' },
      { id: 'nadowli-kaleo-district', name: 'Nadowli-Kaleo District Assembly', type: 'District', capital: 'Nadowli' },
      { id: 'jirapa-municipal', name: 'Jirapa Municipal Assembly', type: 'Municipal', capital: 'Jirapa' },
      { id: 'lambussie-district', name: 'Lambussie District Assembly', type: 'District', capital: 'Lambussie' },
      { id: 'lawra-municipal', name: 'Lawra Municipal Assembly', type: 'Municipal', capital: 'Lawra' },
      { id: 'nandom-district', name: 'Nandom District Assembly', type: 'District', capital: 'Nandom' },
      { id: 'sissala-east-municipal', name: 'Sissala East Municipal Assembly', type: 'Municipal', capital: 'Tumu' },
      { id: 'sissala-west-district', name: 'Sissala West District Assembly', type: 'District', capital: 'Gwollu' },
      { id: 'daffiama-bussie-issa-district', name: 'Daffiama-Bussie-Issa District Assembly', type: 'District', capital: 'Issa' },
    ],
    // Add remaining regions with basic data
    'brong-ahafo': [
      { id: 'sunyani-municipal', name: 'Sunyani Municipal Assembly', type: 'Municipal', capital: 'Sunyani' },
      { id: 'sunyani-west-district', name: 'Sunyani West District Assembly', type: 'District', capital: 'Odumase' },
      { id: 'berekum-municipal', name: 'Berekum Municipal Assembly', type: 'Municipal', capital: 'Berekum' },
      { id: 'dormaa-central-municipal', name: 'Dormaa Central Municipal Assembly', type: 'Municipal', capital: 'Dormaa Ahenkro' },
      { id: 'dormaa-east-district', name: 'Dormaa East District Assembly', type: 'District', capital: 'Wamfie' },
      { id: 'dormaa-west-district', name: 'Dormaa West District Assembly', type: 'District', capital: 'Nkrankwanta' },
      { id: 'jaman-south-municipal', name: 'Jaman South Municipal Assembly', type: 'Municipal', capital: 'Drobo' },
      { id: 'jaman-north-district', name: 'Jaman North District Assembly', type: 'District', capital: 'Sampa' },
      { id: 'tano-south-municipal', name: 'Tano South Municipal Assembly', type: 'Municipal', capital: 'Bechem' },
      { id: 'tano-north-district', name: 'Tano North District Assembly', type: 'District', capital: 'Duayaw Nkwanta' },
      { id: 'wenchi-municipal', name: 'Wenchi Municipal Assembly', type: 'Municipal', capital: 'Wenchi' },
      { id: 'techiman-municipal', name: 'Techiman Municipal Assembly', type: 'Municipal', capital: 'Techiman' },
      { id: 'techiman-north-district', name: 'Techiman North District Assembly', type: 'District', capital: 'Tuobodom' },
      { id: 'nkoranza-south-municipal', name: 'Nkoranza South Municipal Assembly', type: 'Municipal', capital: 'Nkoranza' },
      { id: 'nkoranza-north-district', name: 'Nkoranza North District Assembly', type: 'District', capital: 'Busunya' },
      { id: 'kintampo-south-district', name: 'Kintampo South District Assembly', type: 'District', capital: 'Kintampo' },
      { id: 'kintampo-north-municipal', name: 'Kintampo North Municipal Assembly', type: 'Municipal', capital: 'Kintampo' },
      { id: 'atebubu-amantin-municipal', name: 'Atebubu-Amantin Municipal Assembly', type: 'Municipal', capital: 'Atebubu' },
      { id: 'sene-west-district', name: 'Sene West District Assembly', type: 'District', capital: 'Tato Battor' },
      { id: 'sene-east-district', name: 'Sene East District Assembly', type: 'District', capital: 'Kajaji' },
      { id: 'pru-west-district', name: 'Pru West District Assembly', type: 'District', capital: 'Drobo' },
      { id: 'pru-east-district', name: 'Pru East District Assembly', type: 'District', capital: 'Yeji' },
      { id: 'banda-district', name: 'Banda District Assembly', type: 'District', capital: 'Banda Ahenkro' },
      { id: 'asutifi-north-district', name: 'Asutifi North District Assembly', type: 'District', capital: 'Kenyasi' },
      { id: 'asutifi-south-district', name: 'Asutifi South District Assembly', type: 'District', capital: 'Hwidiem' },
      { id: 'asunafo-north-municipal', name: 'Asunafo North Municipal Assembly', type: 'Municipal', capital: 'Goaso' },
      { id: 'asunafo-south-district', name: 'Asunafo South District Assembly', type: 'District', capital: 'Kukuom' },
    ],
    'western-north': [
      { id: 'wiawso-municipal', name: 'Wiawso Municipal Assembly', type: 'Municipal', capital: 'Sefwi Wiawso' },
      { id: 'bibiani-anhwiaso-bekwai-municipal', name: 'Bibiani-Anhwiaso-Bekwai Municipal Assembly', type: 'Municipal', capital: 'Bibiani' },
      { id: 'aowin-municipal', name: 'Aowin Municipal Assembly', type: 'Municipal', capital: 'Enchi' },
      { id: 'suaman-district', name: 'Suaman District Assembly', type: 'District', capital: 'Dadieso' },
      { id: 'bodi-district', name: 'Bodi District Assembly', type: 'District', capital: 'Bodi' },
      { id: 'juaboso-district', name: 'Juaboso District Assembly', type: 'District', capital: 'Juaboso' },
      { id: 'bia-east-district', name: 'Bia East District Assembly', type: 'District', capital: 'Adabokrom' },
      { id: 'bia-west-district', name: 'Bia West District Assembly', type: 'District', capital: 'Essam' },
      { id: 'akontombra-district', name: 'Akontombra District Assembly', type: 'District', capital: 'Akontombra' },
    ],
    'ahafo': [
      { id: 'goaso-municipal', name: 'Asunafo North Municipal Assembly', type: 'Municipal', capital: 'Goaso' },
      { id: 'kukuom-district', name: 'Asunafo South District Assembly', type: 'District', capital: 'Kukuom' },
      { id: 'kenyasi-district', name: 'Asutifi North District Assembly', type: 'District', capital: 'Kenyasi' },
      { id: 'hwidiem-district', name: 'Asutifi South District Assembly', type: 'District', capital: 'Hwidiem' },
      { id: 'tano-north-district', name: 'Tano North District Assembly', type: 'District', capital: 'Duayaw Nkwanta' },
      { id: 'tano-south-municipal', name: 'Tano South Municipal Assembly', type: 'Municipal', capital: 'Bechem' },
    ],
    'bono': [
      { id: 'sunyani-municipal', name: 'Sunyani Municipal Assembly', type: 'Municipal', capital: 'Sunyani' },
      { id: 'sunyani-west-district', name: 'Sunyani West District Assembly', type: 'District', capital: 'Odumase' },
      { id: 'berekum-municipal', name: 'Berekum Municipal Assembly', type: 'Municipal', capital: 'Berekum' },
      { id: 'dormaa-central-municipal', name: 'Dormaa Central Municipal Assembly', type: 'Municipal', capital: 'Dormaa Ahenkro' },
      { id: 'dormaa-east-district', name: 'Dormaa East District Assembly', type: 'District', capital: 'Wamfie' },
      { id: 'dormaa-west-district', name: 'Dormaa West District Assembly', type: 'District', capital: 'Nkrankwanta' },
      { id: 'jaman-south-municipal', name: 'Jaman South Municipal Assembly', type: 'Municipal', capital: 'Drobo' },
      { id: 'jaman-north-district', name: 'Jaman North District Assembly', type: 'District', capital: 'Sampa' },
      { id: 'wenchi-municipal', name: 'Wenchi Municipal Assembly', type: 'Municipal', capital: 'Wenchi' },
      { id: 'banda-district', name: 'Banda District Assembly', type: 'District', capital: 'Banda Ahenkro' },
    ],
    'bono-east': [
      { id: 'techiman-municipal', name: 'Techiman Municipal Assembly', type: 'Municipal', capital: 'Techiman' },
      { id: 'techiman-north-district', name: 'Techiman North District Assembly', type: 'District', capital: 'Tuobodom' },
      { id: 'nkoranza-south-municipal', name: 'Nkoranza South Municipal Assembly', type: 'Municipal', capital: 'Nkoranza' },
      { id: 'nkoranza-north-district', name: 'Nkoranza North District Assembly', type: 'District', capital: 'Busunya' },
      { id: 'kintampo-south-district', name: 'Kintampo South District Assembly', type: 'District', capital: 'Kintampo' },
      { id: 'kintampo-north-municipal', name: 'Kintampo North Municipal Assembly', type: 'Municipal', capital: 'Kintampo' },
      { id: 'atebubu-amantin-municipal', name: 'Atebubu-Amantin Municipal Assembly', type: 'Municipal', capital: 'Atebubu' },
      { id: 'sene-west-district', name: 'Sene West District Assembly', type: 'District', capital: 'Tato Battor' },
      { id: 'sene-east-district', name: 'Sene East District Assembly', type: 'District', capital: 'Kajaji' },
      { id: 'pru-west-district', name: 'Pru West District Assembly', type: 'District', capital: 'Drobo' },
      { id: 'pru-east-district', name: 'Pru East District Assembly', type: 'District', capital: 'Yeji' },
    ],
    'oti': [
      { id: 'krachi-east-municipal', name: 'Krachi East Municipal Assembly', type: 'Municipal', capital: 'Dambai' },
      { id: 'krachi-west-district', name: 'Krachi West District Assembly', type: 'District', capital: 'Kete Krachi' },
      { id: 'krachi-nchumuru-district', name: 'Krachi Nchumuru District Assembly', type: 'District', capital: 'Chinderi' },
      { id: 'nkwanta-south-municipal', name: 'Nkwanta South Municipal Assembly', type: 'Municipal', capital: 'Nkwanta' },
      { id: 'nkwanta-north-district', name: 'Nkwanta North District Assembly', type: 'District', capital: 'Kpassa' },
      { id: 'biakoye-district', name: 'Biakoye District Assembly', type: 'District', capital: 'Nkonya Ahenkro' },
      { id: 'jasikan-district', name: 'Jasikan District Assembly', type: 'District', capital: 'Jasikan' },
      { id: 'kadjebi-district', name: 'Kadjebi District Assembly', type: 'District', capital: 'Kadjebi' },
    ],
    'savannah': [
      { id: 'bole-district', name: 'Bole District Assembly', type: 'District', capital: 'Bole' },
      { id: 'sawla-tuna-kalba-district', name: 'Sawla-Tuna-Kalba District Assembly', type: 'District', capital: 'Sawla' },
      { id: 'west-gonja-municipal', name: 'West Gonja Municipal Assembly', type: 'Municipal', capital: 'Damongo' },
      { id: 'central-gonja-district', name: 'Central Gonja District Assembly', type: 'District', capital: 'Buipe' },
      { id: 'east-gonja-municipal', name: 'East Gonja Municipal Assembly', type: 'Municipal', capital: 'Salaga' },
      { id: 'north-gonja-district', name: 'North Gonja District Assembly', type: 'District', capital: 'Daboya' },
    ],
    'north-east': [
      { id: 'chereponi-district', name: 'Chereponi District Assembly', type: 'District', capital: 'Chereponi' },
      { id: 'east-mamprusi-municipal', name: 'East Mamprusi Municipal Assembly', type: 'Municipal', capital: 'Gambaga' },
      { id: 'west-mamprusi-municipal', name: 'West Mamprusi Municipal Assembly', type: 'Municipal', capital: 'Walewale' },
      { id: 'mamprugu-moagduri-district', name: 'Mamprugu-Moagduri District Assembly', type: 'District', capital: 'Yagaba' },
      { id: 'yunyoo-district', name: 'Yunyoo District Assembly', type: 'District', capital: 'Yunyoo' },
      { id: 'nalerigu-gambaga-district', name: 'Nalerigu-Gambaga District Assembly', type: 'District', capital: 'Nalerigu' },
    ],
  }
};

export async function GET(request: Request) {
  const { searchParams } = new URL(request.url);
  const regionId = searchParams.get('region');

  try {
    if (regionId) {
      // Return municipalities for specific region
      const municipalities = GHANA_COMPLETE_DATA.municipalities[regionId] || [];
      return NextResponse.json({
        success: true,
        data: municipalities,
        region: GHANA_COMPLETE_DATA.regions.find(r => r.id === regionId)
      });
    } else {
      // Return all regions
      return NextResponse.json({
        success: true,
        data: {
          regions: GHANA_COMPLETE_DATA.regions,
          totalMunicipalities: Object.values(GHANA_COMPLETE_DATA.municipalities).flat().length
        }
      });
    }
  } catch (error) {
    console.error('Error fetching Ghana municipalities:', error);
    return NextResponse.json(
      { success: false, error: 'Failed to fetch municipalities data' },
      { status: 500 }
    );
  }
}
